export interface IRuna {
  title: string;
  image?: string;
  content?: string;
  details?: string;
  detailsdn?: string;
  message?: string;
  messagetitle?: string;
  titleamulet?: string;
  amulet?: string;
  keyup?: string;
  keydn?: string;
  keytitle?: string;
  keywords?: string;
  keywordsdn?: string;
  prev?: string;
  next?: string;
}

interface IRunaList {
  [key: string]: IRuna;
}

export const runes: IRunaList = {
  fehu: {
    title: "Fehu",
    image: "/pngs/FEHU.png",
    keywords: "Speranță • Succes • Determinare",
    keywordsdn: "Probleme • Impedimente • Alegeri greșite",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet:
      "Fehu protjează proprietatea noastră, oamenii pe care îi iubim. Poate servi pentru a consolida o situație economică sau o relație sentimentală. Ne învață să ne recunoaștem valoarea în viața noastră. Încurajează noi proiecte și creativitatea.",
    messagetitle: "Mesajul:",
    message:
      "Ceea ce ne conduce la adevărata fericire, nu are nimic de-a face cu bogăția materială, ci, mai degrabă cu dragostea de viață, cu cei dragi nouă și cu devotamentul față de Dumnezeu.",
    details:
      "Guvernată de Freyr, preotul-rege, sau Freya, în rolul fecundității și al fertilității. Denotă bogăție, prosperitate, fericire, care implică un mod de acțiune drept și cinstit. Printr-un comportament ghidat de generozitatea și spiritul umanitar, ne putem deschide la viață, lăsăm să curgă energia acesteia în noi, obținând toate beneficiile pe care le merităm. Când extragem această Rună, înseamnă că ne îndreptăm în direcția cea bună, facem alegerile corecte, care ne vor conduce cu siguranță la realizare. Acum ne simțim capabili să împărțim, în mod liber, ceea ce avem, pentru că am dobândit capacitatea de a percepe care este echilibrul corect între a da și a primi. Avere bruscă, suces în dragoste și în afaceri.",
    detailsdn:
      "Fehu inversat poate indica pierderea a ceva și nemulțumire. Pot exista probleme cu gestionarea sau întâmpinăm dificultăți în a produce ceva. Ar putea fi vorba de o lipsă de bani, ca să trăim așa cum ne-am dori sau putem munci din greu, fără a fi capabili de a câștiga suficient. Pe lângă toate acestea, am putea avea dificultăți în a ne recunoaște valoarea, nepermițând energiei de care avem nevoie să intre. Motivele care ne conduc să fim în această stare de privare și de nemulțumire ar putea fi legate de modul în care acționăm, calculat, pentru a ieși în câștig. În condituare suntem cuprinși de teama de a pierde ceva, gonim după o falsă siguranță.",
    keytitle: "Gratitudine și generozitate",
    keyup:
      "noroc meritat, stabilitate financiară, utilizare în comun, succes în dragoste, prosperitate",
    keydn:
      "rău, gelozie, invidie, lăcomie, pierderi economice, eșecuri, sclavie, datorii",
    prev: "othala",
    next: "uruz",
  },
  uruz: {
    title: "Uruz",
    image: "/pngs/URUZ.png",
    keywords: "Sănătate • Rezistență • Spirit de voință",
    keywordsdn: "Imobilitate • Lipsă de energie • Fragilitate",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet:
      "Insuflă vitalitate, curaj în fața obstacolelor și ajută la eliminarea îndoielilor și a temerilor. Dă determinare pentru realizarea de noi proiecte (în relații, la locul de muncă, în afaceri), luciditate și curaj de a face față unor decizii importante, atunci când avem acest drept.",
    messagetitle: "Mesajul:",
    message:
      "Dă putere, vitalitate și determinare în fața obstacolelor, ajută la depășirea nesiguranței și îndoielilor. Întărește sănătatea și îndepărtează bolile.",
    details:
      "Este guvernată de Ymir, gigantul instinctelor primare dezlănțuite. Indică faptul că avem multă energie, pe care știm să o gestionăm cel mai bine pentru a ne satisface nevoile și pentru a vedea cu claritate realitatea. Suntem conștienți de valoarea noastră, de capacitatea noastră fizică și mentală: este timpul să ne eliberăm energiile pentru a obține ceea ce ne dorim. Cu mult curaj și determinare, ne putem îndeplini dorințele, putem depăși provocările pe care viața ni le oferă și putem depăși obstacolele pe această cale. Ar trebui, totuși, să dezvoltăm capacitatea de a gândi, înainte de a acționa, să ne cântărim acțiunile și să ne calibrăm energiile: calmul este o calitate necesară în realizarea cu succes a obiectivelor vieții.",
    detailsdn:
      "Uruz inversat relevă pierderea controlului, incapacitatea de a discerne între ficțioune și realitate, între bine și rău. De asemena, indică disperare, oboseală fizică, nervozitate, frică, incapacitatea de a ne controla cele mai întunecate instincte. Sau, dimpotrivă poate dezvălui o stare de depresie, incapacitatea de a experimenta plăcerea de orice fel, aplatizare emoțională, ca și cum ne-am simți într-o fază de stagnare: Energia noastră pare să fie blocată și nu poate să curgă liber. Astfel, este necesar ca părțile blocate să se exprime și să fie eliberate cât mai curând posibil, în caz contrar există riscul de a se transforma în ceva distructiv, pentru noi înșine sau pentru alții. Ar trebui să fim plini de calm, de reflecție și de curaj.",
    keytitle: "Instinctul de supraviețuire",
    keyup:
      "tărie fizică și morală, curaj, vitalitate, inițiativă, independență, inventivitate",
    keydn:
      "ferocitate, masculinitate, rigiditate, amorțeală, agresiune, dependență, imobilitate",
      prev: "fehu",
      next: "thurisaz",
  },
  thurisaz: {
    title: "Thurisaz",
    image: "/pngs/THURISAZ.png",
    keywords: "Succes • Protecție • Putere",
    keywordsdn: "Meditație • Discreditare • Prundență",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet:
      "Întărește apărarea împotriva dușmanilor exteriori și a celor din lăuntrul nostru. Promovează luciditatea, capaditatea de reflecție, calmul, în evaluarea soluției optime spre a face față dificultăților, pentru a începe cu modificarea părților mai fragile din noi înșine.",
    messagetitle: "Mesajul:",
    message:
      "Devenind conștienți de ceea ce ne este mai scump, trebuie să ascuțim armele ca să-i apărăm. Succesul împotriva inamicului se obține atunci când el ne găsește pregătiți.",
    details: "Guvernată de către Thor, gigantul războiului și al frigului. Ea simbolizează puterea de apărare față de tot ceea ce reprezintă o amenințare pentru noi sau pentru cei de care suntem legați afectiv. Este ca și cum am fi actori într-un duel cu un inamic, iar din această luptă putem deveni mai conștienți de slăbiciunile noastre și de ceea ce avem nevoie pentru a fi mai puternici. Devenim mai conștienți de spațiile noastre, de granițele noastre, de relațiile noastre, de interesele, de sănătatea și de munca noastră. Aceasta este o oportunitate de a ne afirma și de a apăra ceea ce avem, demonstrând curaj în confruntarea cu inamicul. Acum suntem capabili să ne protejăm, să nu ne temem de nimic și că putem conta pe noi înșine.",
    detailsdn: "Este un avertisment de a fi gata la timp, pentru a face față evenimentelor neprevăzute din viață. Trebuie să ne consolidăm apărarea sau să o slăbim, în funcție de situație. Trebuie să fim foarte lucizi și să apreciem valoarea reală a evenimentelor. Trebuie să ne perfecționăm armele și să punem la cale un plan inteligent, pentru a face față inamicului și pericolelor de la orizont. În acest moment nu trebuie să așteptăm în mod pasiv, ci să acționăm acum în mod decisiv pentru a îndrepta situația în favoarea noastră. Dacă ne lăsăm duși de evenimente, vom risca să fim copleșiți și să cedăm.",
    keytitle: "Cunfruntarea cu dușmanul",
    keyup:
      "rezistență fizică și putere morală, protecție și apărare, capacitate de regenerare, decizii corecte.",
    keydn:
      "fragilitate, conflict, confuzie, atacuri de la dușmani, răutate, situații neprevăzute, suferință fizică.",
      prev: "uruz",
      next: "ansuz",
    },
  ansuz: {
    title: "Ansuz",
    image: "/pngs/ANSUZ.png",
    keywords: "Sfat înțelept • Ajutor • Cadou",
    keywordsdn: "Înșelătorie • Falsitate • Perfidie",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet:
      "Ne întărește capacitatea de a fi creativi, constructivi și de a vedea în mod clar realitatea. Deschide comunicarea noastră cu sfera divină. Crește capacitatea noastră de a comunica cu ceilalți și cu noi înșine. Ne permite să ne exprimăăm esența cu o mai mare libertate.",
    messagetitle: "Mesajul:",
    message: "Acum trebuie să ne îndepărtăm de tentația de a da înapoi sau de a îngheța într-o stare de negativism. Trebuie să luptăm cu mult curaj pentru propria creștere.",
    details: "Guvernată de Odin, zeul cuvântului, al magiei, al șamanilor și al morții. Suntem într-o stare de claritate mentală, de conștientizare, în armonie perfectă cu sfera divină: este ca și cum energia curge liber în armonie cu universul, ajutată de sfera divină. Spiritul nostru ne vorbește în mod constant, putem auzi vibrația vocii sale în noi, ar trebui să-i urmăm sfatul și să ne lăsăm ghidași cu încredere în el. Este momentul în care putem înțelege viața în simplitatea și în claritatea sa, iar barierele par să dispară. Lumina căii personale ne strălucește în ochi, deoarece acțiunile și gândurile noastre sunt pure, oneste și clare. Suntem pe calea înțelepciunii și a evoluției.",
    detailsdn: "Aceasta indică o perioadă dificilă: când te simți pierdut sau prins în ghiarele egoului, umbrit de individualism și lăcomie, este ca și cum am fi pierdut calea cea dreaptă. Suntem deranjați de cuvintele altora sau ne ascundem de teama de a ne expune, ca și cum ne-ar fi rușine de ceea ce suntem. Ne mințim pe noi înșine, nu avem curajul să vedem realitatea și atragem oameni de neîncredere, care ar putea complota în spatele nostru sau ar putea spune minciuni. Acem nevoie de îndrumarea unei persoane înțeleptte care ne poate aduce din nou pe calea cea bună, care ar putea să ne permită să găsim partea noastră adevărată. Ceea ce atragem este rezultatul agitației din noi.",
    keytitle: "Sunetul sufletului",
    keyup:
      "vindecare, comunicare, înțelepciune, inspirație, gândire, spiritualitate, adevăr.",
    keydn:
      "înșelăciune, minciuni, răutate, nevroze, trădare, lipsă de loialitate, infidelitate, frică, egoism.",
      prev: "thurisaz",
      next: "raido",
    },
  raido: {
    title: "Raido",
    image: "/pngs/RAIDO.png",
    keywords: "Calea cea dreaptă • Echilibru • Justiție",
    keywordsdn: "Complicații • Probleme • Obstacole",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Ne permite să ne deschidem mințile spre o cunoaștere mai profundă. Ne încurajează extnderea conștiinței. Insuflă energie constructivă și de curaj pentru a învinge dragonii (demonii) interiori. Ne ajută să ne lansăm într-o călătorie, în condiții de siguranță. Favorizează schimbări și deblochează situații.",
    messagetitle: "Mesajul:",
    message: "Nu putem permite ca acel ceva sau cineva să decidă viașța noastră: Noi suntem cei care trebuie să o dirijăm și să o conducem spre mai bine.",
    details: "Guvernată de Valkirii, zeițe războinice. Am fost în măsură să rezolvăm într-un mod pozitiv una sau mai multe situații problemă ale vieții noastre. Suntem gata să ne bucurăm de rezultate, de succesele noastre și cu bucurie putem gusta din frumusețea călătoriei noastre. Raido ne vorbește și ne spune că un fragment din calea nostră este parcurs și că o nouă călătorie este pe cale să înceapă sau a început deja: este ca și cum am fi făcut un pas important, am traversat o poartă, este ca și cum am fi intrat într-un nou nivel de conștiință. Acum suntem pregătiți pentru experiențe noi, bazându-ne pe ceea ce am învățat. Putem face față provorărilor vieții, trecând alte porți, atingând alte scopuri. Calea ne-a adus, cu siguranță, mai aproape de destinația aleasă.",
    detailsdn: "Există probleme de-a lungul drumului, iar dificultățile. îndoielile și temerile în fața obstacolelor ne împiedică să facem un pas important. În acest moment, nu reușim să acceptăm provorările vieții, nu le putem contesta pentru a crește și progresa. Este ca și cum nu putem stăpâni un cal în galop, riscând să fim aruncați din șa sau să accidentăm pe cineva, în graba nebună. Fugim de realitate, de responsabilitățile noastre, de sarcinile noastre de dezvoltare. Putem fi deranjați de oameni meschini, care nu sunt de încredere, care ne fac să pierdem calea cea dreaptă. Există metode periculoase (alcool, droguri, sex) care ne pot da sentimentul, iluzoriu, că ajungem la destinație, dar cu siguranță nu este adevărat.",
    keytitle: "Dragonul, fata, comoara.",
    keyup: "călătorie, căutare, proces în curs de desfășurare, promovare, inițiativă, noi intreprinderi.",
    keydn: "involuție, încetinire, pirdere de luciditate, renunțare, senzație de eșec.",
    prev: "ansuz",
    next: "kenaz",
  },
  kenaz: {
    title: "Kenaz",
    image: "/pngs/KENAZ.png",
    keywords: "Vindecare • Noi orizonturi • Renaștere",
    keywordsdn: "Obstacole • Iresponsabilitate • Involuție",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Promovează procesul de transformare, de renaștere și de vindecare. Înlătură întunericul și frigul din sufletul nostru. Luminează ceea ce nu este clar. Ne arată soluțiile potrivite care ne pot ajuta să procedăm în mod corespunzător. Ne eliberează de lanțurile trecutului.",
    messagetitle: "Mesajul:",
    message: "Nu trebuie să bâjbâim în întuneric și să ne lăsăm trași de evenimente, fără a avea un scop. Treuie să urmăm cu încredere calea inimii!",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "Purificarea",
    keyup: "renaștere, vindecare, progres, claritate, iluminare, înțelegere, revelație.",
    keydn: "haos mental, ignoranță, imobilitate, monotonie, boală, superficialitate, aroganță.",
    prev: "raido",
    next: "gebo",
  },
  gebo: {
    title: "Gebo",
    image: "/pngs/GEBO.png",
    keywords: "Uniune Amoroasă • Uniunie cu Dumnezeu",
    keywordsdn: "",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Promovează și îmtărește relațiile de dragoste, de căsătorie, de prietenie, de afacer și de muncă. Ne îndeamnă să fim primitori, deschiși la dispoziția altora, stimulându-le acestora aceeași atitudine față de noi. Runa susține unirea noastră cu sfera divină.",
    messagetitle: "Mesajul:",
    message: "În existența noastră am învățat să primim și să oferim iubire din abundență. Din acest motiv, putem trăi în pace, în armonie și în liniște.",
    details: "xxxx",
    detailsdn: "",
    keytitle: "Relație",
    keyup: "senzație de dragoste, prietenie, cadouri, fraternitate, împărtășire, armonie, echilibru, schimb, generozitate, colaborare, echitate, solidaritate, alianță, complicitate, recunoștință, empatie, înțelegere.",
    keydn: "",
    prev: "kenaz",
    next: "wunjo",
  },
  wunjo: {
    title: "Wunjo",
    image: "/pngs/WUNJO.png",
    keywords: "Realizări • Speranță • Inocență",
    keywordsdn: "Dezechilibru • Insucces • Indolență",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Conferă vitalitate, fericire, optimism și entuziasm pentru tot ce trăim. Insuflă curajul de a fi fericit și de a lăsa să intre norocul în viața noastră. Ne dă încredere în noi și de aici, dorința de a face noi proiecte. Insuflă speranță în viitor.",
    messagetitle: "Mesajul:",
    message: "Soluția este de a depăși starea negativă în care ne eflăm: doar prin acceptarea a ceea ce s-a întâmplat putem renaște.",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "Vindecare",
    keyup: "autoîmplinire, fericire, succes, glorie, speranță, sănătate, armonie.",
    keydn: "eșecuri, depresie, sărăcie, singurătate, pesimism, comportament excesiv.",
    prev: "gebo",
    next: "hagalaz",
  },
  hagalaz: {
    title: "Hagalaz",
    image: "/pngs/HAGALAZ.png",
    keywords: "Schimbări • Naștere • Ruptură",
    keywordsdn: "",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Ajută la deblocarea din situații de stagnare și neproductivitate. Ajută la ruperea din tiparele vechi, permițându-ne să intrăm în contact cu cea mai adevărată și mai autentică parte din noi. Ne eliberează din lanțurile care ne țin încătușați într-un trecut care nu ne ajută să creștem.",
    messagetitle: "Mesajul:",
    message: "Trebuie să ne mișcăm mai departe fără să ne oprim, chiar dacă trecem printr-o perioadă dificilă, care ne poate speria. Când avem curaj să ne pierdem și să mergem mai departe, renaștem.",
    details: "xxxx",
    detailsdn: "",
    keytitle: "Schimbare de plan.",
    keyup: "purificare, modificare de forme prestabilite, teste, cale de creștere, explorare, experimentare, libertate, reînnoire, reconstrucție, naștere, moarte, îmbunătățire, agravare.",
    keydn: "",
    prev: "wunjo",
    next: "nauthiz",
  },
  nauthiz: {
    title: "Nauthiz",
    image: "/pngs/NAUTHIZ.png",
    keywords: "Prudență • Rezistență • Voință",
    keywordsdn: "Suferință • Durere • Dificultate",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "Încercări extreme.",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "hagalaz",
    next: "isa",
  },
  isa: {
    title: "Isa",
    image: "/pngs/ISA.png",
    keywords: "Liniște • Concentrare • Raționament",
    keywordsdn: "",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "Detașare",
    keyup: "xxxxx",
    keydn: "",
    prev: "nauthiz",
    next: "jera",
  },
  jera: {
    title: "Jera",
    image: "/pngs/JERA.png",
    keywords: "Rezultate • Răbdare • Creștere",
    keywordsdn: "",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "Natura ciclică a vieții",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "isa",
    next: "eihwaz",
  },
  eihwaz: {
    title: "Eihwaz",
    image: "/pngs/EIHWAZ.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "jera",
    next: "perthrc",
  },
  perthrc: {
    title: "Perthrc",
    image: "/pngs/PERTHRC.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "eihwaz",
    next: "algiz",
  },
  algiz: {
    title: "Algiz",
    image: "/pngs/ALGIZ.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "perthrc",
    next: "sowilo",
  },
  sowilo: {
    title: "Sowilo",
    image: "/pngs/SOWILO.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "algiz",
    next: "tiewaz",
  },
  tiewaz: {
    title: "Tiewaz",
    image: "/pngs/TIEWAZ.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "sowilo",
    next: "berkana",
  },
  berkana: {
    title: "Berkana",
    image: "/pngs/BERKANA.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "tiewaz",
    next: "ehwaz",
  },
  ehwaz: {
    title: "Ehwaz",
    image: "/pngs/EHWAZ.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "berkana",
    next: "mannaz",
  },
  mannaz: {
    title: "Mannaz",
    image: "/pngs/MANNAZ.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "ehwaz",
    next: "laguz",
  },
  laguz: {
    title: "Laguz",
    image: "/pngs/LAGUZ.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "mannaz",
    next: "inguz",
  },
  inguz: {
    title: "Inguz",
    image: "/pngs/INGUZ.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "laguz",
    next: "dagaz",
  },
  dagaz: {
    title: "Dagaz",
    image: "/pngs/DAGAZ.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "inguz",
    next: "othala",
  },
  othala: {
    title: "Othala",
    image: "/pngs/OTHALA.png",
    keywords: " •  • ",
    keywordsdn: " •  • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "xxxx",
    messagetitle: "Mesajul:",
    message: "xxxxx",
    details: "xxxx",
    detailsdn: "xxx",
    keytitle: "xxxxx",
    keyup: "xxxxx",
    keydn: "xxx",
    prev: "dagaz",
    next: "fehu",
  },
};
