export interface IRuna {
  title: string;
  image?: string;
  content?: string;
  details?: string;
  detailsdn?: string;
  message?: string;
  messagetitle?: string;
  titleamulet?: string;
  amulet?: string;
  keyup?: string;
  keydn?: string;
  keytitle?: string;
  keywords?: string;
  keywordsdn?: string;
  prev?: string;
  next?: string;
}

interface IRunaList {
  [key: string]: IRuna;
}

export const runes: IRunaList = {
  fehu: {
    title: "Fehu",
    image: "/pngs/FEHU.png",
    keywords: "Speranță • Succes • Determinare",
    keywordsdn: "Probleme • Impedimente • Alegeri greșite",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet:
      "Fehu protjează proprietatea noastră, oamenii pe care îi iubim. Poate servi pentru a consolida o situație economică sau o relație sentimentală. Ne învață să ne recunoaștem valoarea în viața noastră. Încurajează noi proiecte și creativitatea.",
    messagetitle: "Mesajul:",
    message:
      "Ceea ce ne conduce la adevărata fericire, nu are nimic de-a face cu bogăția materială, ci, mai degrabă cu dragostea de viață, cu cei dragi nouă și cu devotamentul față de Dumnezeu.",
    details:
      "Guvernată de Freyr, preotul-rege, sau Freya, în rolul fecundității și al fertilității. Denotă bogăție, prosperitate, fericire, care implică un mod de acțiune drept și cinstit. Printr-un comportament ghidat de generozitatea și spiritul umanitar, ne putem deschide la viață, lăsăm să curgă energia acesteia în noi, obținând toate beneficiile pe care le merităm. Când extragem această Rună, înseamnă că ne îndreptăm în direcția cea bună, facem alegerile corecte, care ne vor conduce cu siguranță la realizare. Acum ne simțim capabili să împărțim, în mod liber, ceea ce avem, pentru că am dobândit capacitatea de a percepe care este echilibrul corect între a da și a primi. Avere bruscă, suces în dragoste și în afaceri.",
    detailsdn:
      "Fehu inversat poate indica pierderea a ceva și nemulțumire. Pot exista probleme cu gestionarea sau întâmpinăm dificultăți în a produce ceva. Ar putea fi vorba de o lipsă de bani, ca să trăim așa cum ne-am dori sau putem munci din greu, fără a fi capabili de a câștiga suficient. Pe lângă toate acestea, am putea avea dificultăți în a ne recunoaște valoarea, nepermițând energiei de care avem nevoie să intre. Motivele care ne conduc să fim în această stare de privare și de nemulțumire ar putea fi legate de modul în care acționăm, calculat, pentru a ieși în câștig. În condituare suntem cuprinși de teama de a pierde ceva, gonim după o falsă siguranță.",
    keytitle: "Gratitudine și generozitate",
    keyup:
      "noroc meritat, stabilitate financiară, utilizare în comun, succes în dragoste, prosperitate",
    keydn:
      "rău, gelozie, invidie, lăcomie, pierderi economice, eșecuri, sclavie, datorii",
    prev: "othala",
    next: "uruz",
  },
  uruz: {
    title: "Uruz",
    image: "/pngs/URUZ.png",
    keywords: "Sănătate • Rezistență • Spirit de voință",
    keywordsdn: "Imobilitate • Lipsă de energie • Fragilitate",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet:
      "Insuflă vitalitate, curaj în fața obstacolelor și ajută la eliminarea îndoielilor și a temerilor. Dă determinare pentru realizarea de noi proiecte (în relații, la locul de muncă, în afaceri), luciditate și curaj de a face față unor decizii importante, atunci când avem acest drept.",
    messagetitle: "Mesajul:",
    message:
      "Dă putere, vitalitate și determinare în fața obstacolelor, ajută la depășirea nesiguranței și îndoielilor. Întărește sănătatea și îndepărtează bolile.",
    details:
      "Este guvernată de Ymir, gigantul instinctelor primare dezlănțuite. Indică faptul că avem multă energie, pe care știm să o gestionăm cel mai bine pentru a ne satisface nevoile și pentru a vedea cu claritate realitatea. Suntem conștienți de valoarea noastră, de capacitatea noastră fizică și mentală: este timpul să ne eliberăm energiile pentru a obține ceea ce ne dorim. Cu mult curaj și determinare, ne putem îndeplini dorințele, putem depăși provocările pe care viața ni le oferă și putem depăși obstacolele pe această cale. Ar trebui, totuși, să dezvoltăm capacitatea de a gândi, înainte de a acționa, să ne cântărim acțiunile și să ne calibrăm energiile: calmul este o calitate necesară în realizarea cu succes a obiectivelor vieții.",
    detailsdn:
      "Uruz inversat relevă pierderea controlului, incapacitatea de a discerne între ficțioune și realitate, între bine și rău. De asemena, indică disperare, oboseală fizică, nervozitate, frică, incapacitatea de a ne controla cele mai întunecate instincte. Sau, dimpotrivă poate dezvălui o stare de depresie, incapacitatea de a experimenta plăcerea de orice fel, aplatizare emoțională, ca și cum ne-am simți într-o fază de stagnare: Energia noastră pare să fie blocată și nu poate să curgă liber. Astfel, este necesar ca părțile blocate să se exprime și să fie eliberate cât mai curând posibil, în caz contrar există riscul de a se transforma în ceva distructiv, pentru noi înșine sau pentru alții. Ar trebui să fim plini de calm, de reflecție și de curaj.",
    keytitle: "Instinctul de supraviețuire",
    keyup:
      "tărie fizică și morală, curaj, vitalitate, inițiativă, independență, inventivitate",
    keydn:
      "ferocitate, masculinitate, rigiditate, amorțeală, agresiune, dependență, imobilitate",
      prev: "fehu",
      next: "thurisaz",
  },
  thurisaz: {
    title: "Thurisaz",
    image: "/pngs/THURISAZ.png",
    keywords: "Succes • Protecție • Putere",
    keywordsdn: "Meditație • Discreditare • Prundență",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet:
      "Întărește apărarea împotriva dușmanilor exteriori și a celor din lăuntrul nostru. Promovează luciditatea, capaditatea de reflecție, calmul, în evaluarea soluției optime spre a face față dificultăților, pentru a începe cu modificarea părților mai fragile din noi înșine.",
    messagetitle: "Mesajul:",
    message:
      "Devenind conștienți de ceea ce ne este mai scump, trebuie să ascuțim armele ca să-i apărăm. Succesul împotriva inamicului se obține atunci când el ne găsește pregătiți.",
    details: "Guvernată de către Thor, gigantul războiului și al frigului. Ea simbolizează puterea de apărare față de tot ceea ce reprezintă o amenințare pentru noi sau pentru cei de care suntem legați afectiv. Este ca și cum am fi actori într-un duel cu un inamic, iar din această luptă putem deveni mai conștienți de slăbiciunile noastre și de ceea ce avem nevoie pentru a fi mai puternici. Devenim mai conștienți de spațiile noastre, de granițele noastre, de relațiile noastre, de interesele, de sănătatea și de munca noastră. Aceasta este o oportunitate de a ne afirma și de a apăra ceea ce avem, demonstrând curaj în confruntarea cu inamicul. Acum suntem capabili să ne protejăm, să nu ne temem de nimic și că putem conta pe noi înșine.",
    detailsdn: "Este un avertisment de a fi gata la timp, pentru a face față evenimentelor neprevăzute din viață. Trebuie să ne consolidăm apărarea sau să o slăbim, în funcție de situație. Trebuie să fim foarte lucizi și să apreciem valoarea reală a evenimentelor. Trebuie să ne perfecționăm armele și să punem la cale un plan inteligent, pentru a face față inamicului și pericolelor de la orizont. În acest moment nu trebuie să așteptăm în mod pasiv, ci să acționăm acum în mod decisiv pentru a îndrepta situația în favoarea noastră. Dacă ne lăsăm duși de evenimente, vom risca să fim copleșiți și să cedăm.",
    keytitle: "Cunfruntarea cu dușmanul",
    keyup:
      "rezistență fizică și putere morală, protecție și apărare, capacitate de regenerare, decizii corecte.",
    keydn:
      "fragilitate, conflict, confuzie, atacuri de la dușmani, răutate, situații neprevăzute, suferință fizică.",
      prev: "uruz",
      next: "ansuz",
    },
  ansuz: {
    title: "Ansuz",
    image: "/pngs/ANSUZ.png",
    keywords: "Sfat înțelept • Ajutor • Cadou",
    keywordsdn: "Înșelătorie • Falsitate • Perfidie",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet:
      "Ne întărește capacitatea de a fi creativi, constructivi și de a vedea în mod clar realitatea. Deschide comunicarea noastră cu sfera divină. Crește capacitatea noastră de a comunica cu ceilalți și cu noi înșine. Ne permite să ne exprimăăm esența cu o mai mare libertate.",
    messagetitle: "Mesajul:",
    message: "Acum trebuie să ne îndepărtăm de tentația de a da înapoi sau de a îngheța într-o stare de negativism. Trebuie să luptăm cu mult curaj pentru propria creștere.",
    details: "Guvernată de Odin, zeul cuvântului, al magiei, al șamanilor și al morții. Suntem într-o stare de claritate mentală, de conștientizare, în armonie perfectă cu sfera divină: este ca și cum energia curge liber în armonie cu universul, ajutată de sfera divină. Spiritul nostru ne vorbește în mod constant, putem auzi vibrația vocii sale în noi, ar trebui să-i urmăm sfatul și să ne lăsăm ghidași cu încredere în el. Este momentul în care putem înțelege viața în simplitatea și în claritatea sa, iar barierele par să dispară. Lumina căii personale ne strălucește în ochi, deoarece acțiunile și gândurile noastre sunt pure, oneste și clare. Suntem pe calea înțelepciunii și a evoluției.",
    detailsdn: "Aceasta indică o perioadă dificilă: când te simți pierdut sau prins în ghiarele egoului, umbrit de individualism și lăcomie, este ca și cum am fi pierdut calea cea dreaptă. Suntem deranjați de cuvintele altora sau ne ascundem de teama de a ne expune, ca și cum ne-ar fi rușine de ceea ce suntem. Ne mințim pe noi înșine, nu avem curajul să vedem realitatea și atragem oameni de neîncredere, care ar putea complota în spatele nostru sau ar putea spune minciuni. Acem nevoie de îndrumarea unei persoane înțeleptte care ne poate aduce din nou pe calea cea bună, care ar putea să ne permită să găsim partea noastră adevărată. Ceea ce atragem este rezultatul agitației din noi.",
    keytitle: "Sunetul sufletului",
    keyup:
      "vindecare, comunicare, înțelepciune, inspirație, gândire, spiritualitate, adevăr.",
    keydn:
      "înșelăciune, minciuni, răutate, nevroze, trădare, lipsă de loialitate, infidelitate, frică, egoism.",
      prev: "thurisaz",
      next: "raido",
    },
  raido: {
    title: "Raido",
    image: "/pngs/RAIDO.png",
    keywords: "Calea cea dreaptă • Echilibru • Justiție",
    keywordsdn: "Complicații • Probleme • Obstacole",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Ne permite să ne deschidem mințile spre o cunoaștere mai profundă. Ne încurajează extnderea conștiinței. Insuflă energie constructivă și de curaj pentru a învinge dragonii (demonii) interiori. Ne ajută să ne lansăm într-o călătorie, în condiții de siguranță. Favorizează schimbări și deblochează situații.",
    messagetitle: "Mesajul:",
    message: "Nu putem permite ca acel ceva sau cineva să decidă viașța noastră: Noi suntem cei care trebuie să o dirijăm și să o conducem spre mai bine.",
    details: "Guvernată de Valkirii, zeițe războinice. Am fost în măsură să rezolvăm într-un mod pozitiv una sau mai multe situații problemă ale vieții noastre. Suntem gata să ne bucurăm de rezultate, de succesele noastre și cu bucurie putem gusta din frumusețea călătoriei noastre. Raido ne vorbește și ne spune că un fragment din calea nostră este parcurs și că o nouă călătorie este pe cale să înceapă sau a început deja: este ca și cum am fi făcut un pas important, am traversat o poartă, este ca și cum am fi intrat într-un nou nivel de conștiință. Acum suntem pregătiți pentru experiențe noi, bazându-ne pe ceea ce am învățat. Putem face față provorărilor vieții, trecând alte porți, atingând alte scopuri. Calea ne-a adus, cu siguranță, mai aproape de destinația aleasă.",
    detailsdn: "Există probleme de-a lungul drumului, iar dificultățile. îndoielile și temerile în fața obstacolelor ne împiedică să facem un pas important. În acest moment, nu reușim să acceptăm provorările vieții, nu le putem contesta pentru a crește și progresa. Este ca și cum nu putem stăpâni un cal în galop, riscând să fim aruncați din șa sau să accidentăm pe cineva, în graba nebună. Fugim de realitate, de responsabilitățile noastre, de sarcinile noastre de dezvoltare. Putem fi deranjați de oameni meschini, care nu sunt de încredere, care ne fac să pierdem calea cea dreaptă. Există metode periculoase (alcool, droguri, sex) care ne pot da sentimentul, iluzoriu, că ajungem la destinație, dar cu siguranță nu este adevărat.",
    keytitle: "Dragonul, fata, comoara.",
    keyup: "călătorie, căutare, proces în curs de desfășurare, promovare, inițiativă, noi intreprinderi.",
    keydn: "involuție, încetinire, pirdere de luciditate, renunțare, senzație de eșec.",
    prev: "ansuz",
    next: "kenaz",
  },
  kenaz: {
    title: "Kenaz",
    image: "/pngs/KENAZ.png",
    keywords: "Vindecare • Noi orizonturi • Renaștere",
    keywordsdn: "Obstacole • Iresponsabilitate • Involuție",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Promovează procesul de transformare, de renaștere și de vindecare. Înlătură întunericul și frigul din sufletul nostru. Luminează ceea ce nu este clar. Ne arată soluțiile potrivite care ne pot ajuta să procedăm în mod corespunzător. Ne eliberează de lanțurile trecutului.",
    messagetitle: "Mesajul:",
    message: "Nu trebuie să bâjbâim în întuneric și să ne lăsăm trași de evenimente, fără a avea un scop. Treuie să urmăm cu încredere calea inimii!",
    details: "Guvernată de Surt, gigantul din Țara de Foc. Indică puterea focului, a luminii și a căldurii, dezvăluind un proces de transformare, de alchimizare, de evoluție. Suntem într-un moment de conștientizări profunde care ne luminează calea. Ne rezolvă problemele și elimină tot ceea ce nu ne mai servește, iar dacă există un impediment, acum este ars și transformat. Trebuie să fim dispuși să pierdem ceva pentru a câștiga altceva, să lăsăm să intre în viața noastră ceea ce e nou și ceea ce ne duce la renaștere. Avem capacitatea de a înțelege profund ceea ce putem oferi pentru a găsi adevărul nostru, identitatea noastră. Este ca și cum focul din torță ar ilumina ceea ce suntem cu adevărat acum, în prezent, și ceea ce noi nu vom mai fi.",
    detailsdn: "Ne găsim într-un moment întunecat, ca și cum ne irosim energia într-o situație sau într-o relație. Domnește apatia, plictiseala de rutină și totul pare lipsit de sens. Ne simțim prinși în situații pe care nu le mai dorim, ne simțim de parcă suntem încurcați în ceva ce nu pare să ne aparțină. Trecutul ne apare ca un impediment în calea dezvoltării, ne încetinește calea și creează confuzie în ceea ce privește obiectivele pe care ni le-am propus. Rătăcim confuz în întuneric, fără o strălucire care să ne lumineze calea: suntem la mila evenimentelor și suntem expuși pericolelor. Este un proces în curs de desfășurare, iar după acest moment confuz vine întotdeauna claritatea. Înainte de răsărit, este cel mai întunecat.",
    keytitle: "Purificarea",
    keyup: "renaștere, vindecare, progres, claritate, iluminare, înțelegere, revelație.",
    keydn: "haos mental, ignoranță, imobilitate, monotonie, boală, superficialitate, aroganță.",
    prev: "raido",
    next: "gebo",
  },
  gebo: {
    title: "Gebo",
    image: "/pngs/GEBO.png",
    keywords: "Uniune Amoroasă • Uniunie cu Dumnezeu",
    keywordsdn: "",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Promovează și întărește relațiile de dragoste, de căsătorie, de prietenie, de afacer și de muncă. Ne îndeamnă să fim primitori, deschiși la dispoziția altora, stimulându-le acestora aceeași atitudine față de noi. Runa susține unirea noastră cu sfera divină.",
    messagetitle: "Mesajul:",
    message: "În existența noastră am învățat să primim și să oferim iubire din abundență. Din acest motiv, putem trăi în pace, în armonie și în liniște.",
    details: "Guvernată de Freyr, capul familiei, cu rolul de generozitate, de pace. Indică darul pe care l-am primit de la Dumnezeu, ce poate fi înțeles ca talent individual. Reprezintă relația sacră dintre cei care dau si cei care primesc ceva: simbolizează schimbul de energie dintre cel care oferă darul și cel care îl primește. Într-adevăr, grafic, această Rună intersectează două linii încrucișate, care se interschimbă și creează echilibrul între părți. În prim plan este tema generozității, ca impuls fundamental al actului de a oferi, ceea ce îl face important pe dăruitor și îl onorează. Această Rună, este de asemenea guvernată de Vjofn, zeița armoniei și a reconcilierii, ce stăpânește sentimentul de fraternitate, prietenie, solidaritate, alianță. Gebo spune că trebuie să gândim și să analizăm modurile în care existența noastră se manifestă în asocieri, echilibru și schimburi. Atunci când în viața noastră ne comportăm într-o modalitate deschisă, empatică, iubitoare, curajoasă, prietenoasă și cuprinzătoare, putem spune că ne simțim uniți unii cu alții. Putem fi uniți unii cu alții cu mai multe ocazii și în diferite moduri: prin colaborarea la realizarea unui proiect comun, într-o relație, într-o căsătorie. Așadar, această Rună poate indica o reuniune de bun augur sau consolidarea unei relații care durează o lungă perioadă, atât la nivel afectiv, cât și în domeniul de activitate și de afaceri. Runa poate indica apariția unei noi relații de dragoste, guvernată de armonie și de reciprocitate. De asemenea, se referă la o prosperitate materială, la cadouri și prevede recunoștința și responsabilitatea față de ceea ce am primit.",
    detailsdn: "",
    keytitle: "Relație",
    keyup: "senzație de dragoste, prietenie, cadouri, fraternitate, împărtășire, armonie, echilibru, schimb, generozitate, colaborare, echitate, solidaritate, alianță, complicitate, recunoștință, empatie, înțelegere.",
    keydn: "",
    prev: "kenaz",
    next: "wunjo",
  },
  wunjo: {
    title: "Wunjo",
    image: "/pngs/WUNJO.png",
    keywords: "Realizări • Speranță • Inocență",
    keywordsdn: "Dezechilibru • Insucces • Indolență",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Conferă vitalitate, fericire, optimism și entuziasm pentru tot ce trăim. Insuflă curajul de a fi fericit și de a lăsa să intre norocul în viața noastră. Ne dă încredere în noi și de aici, dorința de a face noi proiecte. Insuflă speranță în viitor.",
    messagetitle: "Mesajul:",
    message: "Soluția este de a depăși starea negativă în care ne eflăm: doar prin acceptarea a ceea ce s-a întâmplat putem renaște.",
    details: "Guvernată de cuplul Freyr si Freya, Wunjo ne conectează cu fericirea, conștientizarea victoriei, cu sentimentul de plentitudine. Ne bucură de plăcerile vieții în toate aspectele sale, depășind temerile, furia, grijile. Putem simți frumusețea vieții în simplitatea ei, ca prin ochii puri și inocenți ai unui copil. Am recuperat contactul cu dimensiunea divină și am devenit înțelepți. Toate acestea ne fac să trăim cu bucurie momentul prezent, unde putem găsi energiile pure ale vieții și ale iubirii. Ne-am câștigat pe noi înșine, pentru că ne-am iertat și am lăsat norocul să vină în viața noastră. Conștiința noastră se extinde.",
    detailsdn: "Ne relevă că ne abatem de la responsabilitățiile noastre, deoarece ne temem de suferință. Realitatea ne apare prea dificilă și se pare că suntem conduși de dorința de a ne refugia în fantezii iluzorii. Poate că suferințele prin care am trecut, ne-au falsificat până la punctul de a nu avea curajul de a lua drumul corect. Sutem plini de amărăciune și de cinism, ne simțim răniți și ne-am pierdut încrederea în noi și în alții. Acest lucru ne-ar putea împinge să fim negativi față de alții, până la a-i pedepsi, sau am putea fi tentați să ne pedepsim chiar pe noi înșine. Această Rună ne invită să reflectăm asupra părților în suferință din noi și asupra viziunii noastre negative despre viață.",
    keytitle: "Bucurie, vindecare",
    keyup: "bucurie, autoîmplinire, fericire, succes, glorie, speranță, sănătate, armonie.",
    keydn: "eșecuri, depresie, sărăcie, singurătate, pesimism, comportament excesiv.",
    prev: "gebo",
    next: "hagalaz",
  },
  hagalaz: {
    title: "Hagalaz",
    image: "/pngs/HAGALAZ.png",
    keywords: "Schimbări • Naștere • Ruptură",
    keywordsdn: "",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Ajută la deblocarea din situații de stagnare și neproductivitate. Ajută la ruperea din tiparele vechi, permițându-ne să intrăm în contact cu cea mai adevărată și mai autentică parte din noi. Ne eliberează din lanțurile care ne țin încătușați într-un trecut care nu ne ajută să creștem.",
    messagetitle: "Mesajul:",
    message: "Trebuie să ne mișcăm mai departe fără să ne oprim, chiar dacă trecem printr-o perioadă dificilă, care ne poate speria. Când avem curaj să ne pierdem și să mergem mai departe, renaștem.",
    details: "Guvernată de Hagal, zeul gheții, simbolizează puterea destinului în existența noastră. Relevă spargerea schemelor și a certitudinilor false. Prin Hagalaz vom scăpa de obiceiurile stereotip și de modul de gestionare a propriei existențe, de identificări depășite, care acum nu mai par a fi o parte din noi. Aceste modificări pot implica perioade dificile, întârzieri sau blocaje (uneori chiar boli), dar aceasta este doar o parte dintr-un proces care ne va duce la unele puncte de cotitură în existență. Tot ceea ce apare rigid, predeterminat, schematic, este pus sub semnul întrebării, este ca și când ai auzit că modul nostru vechi de funcționare nu mai corespunde de mult. Ne simțim prizonieri și vrem să ieșim din cușca constrângerilor (modele, reguli, morală), care ne împiedică libertatea de exprimare. Prin această Rună putem deveni conștienți de ceea ce s-a schimbat cu adevărat în noi și ceea ce se poate schimba în continuare: vechiul este distrus, cu scopul de a crea noul, cu o continuă schimbare între moarte și renaștere. Prin acest proces de schimbare ne dezvoltăm, deveninm mai autentici, ne dezvăluie esența noastră cea mai intimă, ne purifică de trecut, fiind de acord să plătim conturile blocate și să intrăm într-o altă stare de conștiință. Hagalaz poate acționa ca și cum ne-am trezit dintr-un somn profund, făcându-ne să ne recăpătăm treptat conștiința. Pe parcursul acestei perioade, putem fi nesiguri pe picioare, confuzi și cu îndoieli cu privire la modul în care ar trebui să acționăm pentru a face față acestui stadiu, care, în anumite privințe și perspective ar putea să pară traumatic. Ar trebui să înțelegem totuși că, uneori, confuzia duce la înțelepciune.",
    detailsdn: "",
    keytitle: "Schimbare de plan.",
    keyup: "purificare, modificare de forme prestabilite, teste, cale de creștere, explorare, experimentare, libertate, reînnoire, reconstrucție, naștere, moarte, îmbunătățire, agravare.",
    keydn: "",
    prev: "wunjo",
    next: "nauthiz",
  },
  nauthiz: {
    title: "Nauthiz",
    image: "/pngs/NAUTHIZ.png",
    keywords: "Prudență • Rezistență • Voință",
    keywordsdn: "Suferință • Durere • Dificultate",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Insuflă capacitatea de a depăși momentele de neliniște, de anxietate și de frică. Aceasta ajută la depășirea propriilor blocaje și a rigidității lor. Ne îndeamnă să intrăm în contact cu cele mai profunde părți din noi înșine, pentru a reflecta asupra aceea ce suntem și ce avem e schimbat pentru a evolua.",
    messagetitle: "Mesajul:",
    message: "Dacă schimbăm felul în care abordăm viața, suferința ne permite să creștem, pentru că doar atunci când ne lovim de obstacole vom învăța să trecem peste ele.",
    details: "Guvernat de Heimdall, în aspectul său de generare și de generator. Indică un moment dificil: viața ne-a pus în fața unor încercări greu de depășit și ne simțim fragili. Starea de nesiguranță pe care o trăim ne face să ne fie teamă de a face greșeli și de a nu fi deschiși la găsirea de soluții creative, pentru a depăși momentul critic în care ne aflăm. După lăsarea întunericului, se poate întoarce lumina, trebuie doar să învățăm să nu cădem pradă adversităților pe care viața ni le scoate în cale. Prin această cale dificilă putem găsi forța care ne permite să creștem și să ne dezvoltăm capacitatea de a găsi strategiile potrivite, în fața pericolelor care ne pândesc. Este un timp de reflecție și de singurătate, ingredientele necesare pentru creșterea noastră.",
    detailsdn: "Trebuie să ne ascultăm profund și să urmăm cuvintele dictate de inconștient, de instincte. Dacă ne blocăm fluxul interior, riscăm să ne suprimăm cea mai adevărată parte a noastră, riscăm să nu dăm glas nevoilor noastre profunde, care sunt adevăratele noastre motivații. Neascultând vocea inconștientului și împiedicând în mod rigid corzile sufletului să vibreze, putem risca să ne îmbolnăvim. Ne împotrivim suferinței noastre, deoarece ne temem de emoțiile noastre, ne ascundem în spatele a ceva ce nu este al nostru, speriați de partea noastră întunecată.",
    keytitle: "Încercări extreme.",
    keyup: "rezistență, dezvoltarea de virtuți, determinare, tărie interioară, schimbare.",
    keydn: "durere, suferință, vinovăție, constrângere, anxietate, frică, dificultăți, lașitate, negare.",
    prev: "hagalaz",
    next: "isa",
  },
  isa: {
    title: "Isa",
    image: "/pngs/ISA.png",
    keywords: "Liniște • Concentrare • Raționament",
    keywordsdn: "",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Eliberează neliniștile viitorului și regretele trecutului. Ne ajută să găsim concentrarea corectă pentru a reflecta asupra situației și pentru a ne găsi centrul. Insuflă capacitatea de a ne concentra aspra prezentului și ne eliberează de influențele altora.",
    messagetitle: "Mesajul:",
    message: "Pentru a trece peste un obstacol este necesar să ne întoarcem în Sine, să avem răbdarea și puterea de a ști să așteptăm. Soluțiile vor veni numai atunci când suntem pregătiți.",
    details: " Fiind asociata cu înghețul, Runa Isa semnifică blocarea planurilor sau a acțiunilor. În acest caz, se sugerează amânarea activitățiilor întreținute, pentru vremuri mai bune. În cazul în care se asociaza cu conotații pozitive, blocajele sau întârzierile indicate de Isa sunt trecatoare. În plan spiritual, apariția Runei Isa într-un tiraj, semnifică o racire a relațiilor afective cu persoana iubită sau cu anturajul, care - de multe ori este consecința propriilor acțiuni incorecte din trecut, iar în cazul asocierii cu conotații negative, poate prezice chiar și desparțirea. Semnificația sa indică credință rasplatită, împlinirea visurilor, eliberarea de griji; acțiunea și reacțiunea; rezolvarea problemelor, finalizarea fructuoasă a unui proiect, a unei intreprinderi, începerea unei etape noi, superioare, și o schimbare progresiva in bine. Dacă simți că stagnezi, ca nu reușesti lucrurile pe care ți le-ai propus, dar lucrurile vor fi așa, decât doar o perioadă de timp. Situațiile dificile pot fi depașite doar daca te mobilizezi, nu aștepta în zadar să te ajute alții. S-ar putea să trebuiască să renunți la o un mod de gândire învechit sau la niște obiceiuri proaste, pentru ca să mergi mai departe. Nu te lasa controlat, fii tare pe poziția pe care ți-ai ales-o. Ești usor de influențat în această perioadă și nu mai vezi problemele cu adevarat importante.",
    detailsdn: "- - - ",
    keytitle: "Detașare",
    keyup: "meditație, încetinire, izolare, lipsă de lioalitate, moment de reflecție, focalizare, protecție împotriva influențelor externe, iluzii, întârzieri, urăciune, separare, limitări.",
    keydn: "- - -",
    prev: "nauthiz",
    next: "jera",
  },
  jera: {
    title: "Jera",
    image: "/pngs/JERA.png",
    keywords: "Rezultate • Răbdare • Creștere",
    keywordsdn: " - - - ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Ne ajută să tolerăm momentele de așteptare și să depășim perioadele de stres intens. Ne pune în acord cu timpul nostru și cu al altora. Insuflă speranță și încredere, ingredientele necesare pentru a ști cum să așteptăm momentul potrivit recoltării a ceea ce am semănat.",
    messagetitle: "Mesajul:",
    message: "Oferă atenția ta, dăruire și grijă în cultivarea prorpiului teren, dar, de asemenea, înțelepciunea de a ști cum să așteptăm cu răbdare momentul potrivit de recoltare.",
    details: "Guvernată de Sif, soția lui Thor și protectoare a grâului și a culturilor. Acum putem culege roadele pe care le-am cultivat. Suntem artizanii destilului nostru țesând și trasând, am dat o direcție călătoriei noastre. Vom experimenta acum, rezultatele alegerilor noastre din trecut. Suntem mereu în timp, dar dacă nu suntem fericiți și recunostători, vom da o direcție diferită vieții noastre și ceea ce vom secera va fi similar cu ceea ce am semănat. Astfel, să dăm întotdeauna atenție deciziilor pe care le luăm, deoarece acest lucru va avea un impact asupra viitorului nostru. Trebuie să ne dezvoltăm capacitatea de a aștepta încrezători că un eveniment se poate îndeplini printr-un proces gradual de maturizare: nu anticipați vremurile, există riscul de a nu vedea rezultatele dorite și de a strica o situație necesară, in cursul natural de dezvoltare a evenimentelor. Fiecare proces implică un timp de naștere, o perioadă de creștere și un moment al evoluției: numai după acești trei pași se poate ajunge la un rezultat final și definitiv. Timpul nostru de așteptare este revelat ca o energie creatoare care permite obținerea unor rezultate concrete. Astfel, prin decizii și acțiuni înțelepte vom planta semințele viitorului, dar înțelepciunea noastră de va arăta în funcție de capaticatea noastră de a aștepta timpul potrivit de maturizare. Este finalul negativității, este timpul renașterii aspectelor pozitive și al speranței: Runa dezvăluie recolte, recompense, încrederea în viitor și ne invită să plătim prețul acțiunilor noastre, pentru a evităm întâlnirea cu situații negative în viitor.",
    detailsdn: " - - - ",
    keytitle: "Natura ciclică a vieții",
    keyup: "natura ciclică a timpului, aștepatre, maturizare, schimbare, evoluție, creștere, rezultate, încredere, răbdare, speranță, națtere, recoltare, înțelepciune, proces de dezvoltare.",
    keydn: "- - -",
    prev: "isa",
    next: "eihwaz",
  },
  eihwaz: {
    title: "Eihwaz",
    image: "/pngs/EIHWAZ.png",
    keywords: " Tenacitate • Constanță • Rezistență",
    keywordsdn: "- - -",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Insuflă abilitatea de a lua decizii înțelepte și de a face alegeri potrivite. Întărește capacitatea noastră de a depăși conflictele dintre lumea materială și cea spirituală. Alimentează determinarea noastră și ne ajută să transformăm provocările în oportunități.",
    messagetitle: "Mesajul:",
    message: "Nu toate relele vin să ne rănească. Uneori, medicamentele și otrava, binele și răul, pot fi același lucru. Transformăm dificultăți în oportunități.",
    details: "Guvernată de Yr, gardianul focului. Acum ne folosim puterea, vitalitatea și ne putem apăra acel lucru de care ne pasă cel mai mult. Punem în aplicare capacitatea noastră de a transforma adversitatea în ceva pozitiv, puterea de a găsi soluții la probleme. Eihwaz ne arată cum uneori, dificultățile pot fi instrumente pentru a ne întări, astfel, problemele devin oportunități. Depășind frica de moarte și de anihilare, putem lua legătura cu propria putere interioară. Atunci când apare această Rună, înseamnă că gestionăm bine problemele noastre, că ne străduim să învățăm din ele, în loc să ne plângem. Acest lucru ne permite să ne deschidem la noi niveluri ale conștiinței. Când apare această Rună, trebuie să reflectăm asupra modului de raportare la dificultăților pe care le întâlnim: reacționăm cu frică, fugim de probleme renunțând la găsirea de soluții ori putem alege să confruntăm cu determinare și curaj orice provocare pe care viața ne-o prezintă. Eihwaz sugerează care parte din noi trebuie să moară, astfel încât să poată renaște o parte nouă. Trebuie să ne ridicăm și să o luăm de la capăt, trebuie să ne adunăm forțele și să depășim dificultățile care, în cele din urmă, se vor transforma în avantaje. Numai după ce intrăm în contact cu dificultățile, ne vom putea dezvolta puterea de la le preveni și putem învăța cum să deviem blocaje și înfrângeri. În acest fel, ne vom dezvolta abilitatea de a vedea și de a intui unele consecințe, înainte de a acționa.",
    detailsdn: "- - -",
    keytitle: "Depășirea dificultăților",
    keyup: "capacitate de apărare, rezistență, forță interioară, răbdare, fiabilitate, dezvoltare, determinare, inteligență, toleranță, curaj, spirit de luptă, finalizarea cu succes a testelor, capacitatea de a preveni.",
    keydn: "- - -",
    prev: "jera",
    next: "perthrc",
  },
  perthrc: {
    title: "Perthrc",
    image: "/pngs/PERTHRC.png",
    keywords: "Regulile jocului • Noroc",
    keywordsdn: "Incorectitudine • Dependență • Joc periculos",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Promovează procesul de renaștere la nivel fizic și mental. Dezvăluie potențialul nostru ascuns și ne facilitează exprimarea. Aduce entuziasm, fericire, implicare, inspirație. Oferă capacitatea de a trăi în prezent, alegând cele mai pozitive aspecte.",
    messagetitle: "Mesajul:",
    message: "Trucurile și înșelăciunile sunt futile. Viața este un joc și niciodată nu trebuie să renunțăm la zâmbet și la lejeritate, pentru că s-ar putea să ne pierderm.",
    details: "Guvernată de Ve, zeul care vorbește lucrurilor, zeul poeziei magice. Acum reasamblăm piesele trecutului nostru într-un mod nou pentru a putea renaște. Noul mod de viață implică demolarea dificultăților și a necazurilor prin care am trecut, aducând purificare, conștientizare și lumină. Regenerare fizică, emoțională, mentală, spirituală, trebuie doar să învățăm să așteptăm, iar procesul va fi îndeplinit. Ne vom simți în curând cu adevărat reînnoiți, calmi, puternici, liniștiți și plini de bucurie, pe calea noastră. Atitudinea jucăușă, bucuria, lejeritatea și divertismentul ne vor ajuta să uităm de partea întunecată a trecutului și să ne bucurăm de plăcerile dragostei, ale sexului și ale prieteniei.",
    detailsdn: "Nu este bine să ne opunem destinului, din teamă că situația noastră se poate schimba și vom evolua. Trebuie să abandonăm vechile obiceiuri și vechile atitudini. Refuzând să acceptăm lucrurile așa cum sunt, nu putem renaște. Suntem într-o stare de anxietate și de frică, pentru că ceea ce ne înspăimântă este schimbarea. Noi nu vrem să vedem sau să auzim ce se întâmplă în jurul nostru și ne spunem minciuni, înșelându-ne că totul merge bine. Avem nevoie să ne fie distrasă atenția, dar distragerea este doar o modalitate de a scăpa de noi înșine și de situația interioară cu care ne confruntăm. Suntem anchilozați și ne-am obilnuit să trăim o viață fără izbucniri, fără pasiune, fără bucurie.",
    keytitle: "Jocul vieții",
    keyup: "bucurie, râs, joc, soartă, succes, noroc, renaștere, rezolvarea problemelor.",
    keydn: "tristețe, depresie, refuz, degradare, dependență, pericol, forțe incontrolabile.",
    prev: "eihwaz",
    next: "algiz",
  },
  algiz: {
    title: "Algiz",
    image: "/pngs/ALGIZ.png",
    keywords: "Protecție divină • Realizări",
    keywordsdn: "Decepție • Disperare • Sfaturi rele",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Contribuie la consolidarea comunicării cu sfera divină , oferă intuiție și este îndrumarea noastra interioară. Dă curaj și tărie pentru a face față unor situații dificile, pericolelor și amenințărilor pe care le întâmpinăm. Ne protejează pe noi și pe oamenii pe care îi iubim.",
    messagetitle: "Mesajul:",
    message: "Pentru a face față lumii, este nevoie de calități umane, dar privind la sfera divină putem obține ajutor și protecție ce ne iluminează calea.",
    details: "Guvernată de Baldur, acesta indică o protecție prin comunicare și legătură cu sfera divină. Descoperim importanța sacrului în viața noastră și sărbătorim, mulțumindu-i pentru darurile primite. Prin această rună ne putem reconecta energiile universale cu cele individuale spre sfera divină, care ne întărește și ne dă puterea sa. De fapt, comunicând cu divinitatea, putem primi tot ajutorul și sprijinul de care avem nevoie, ne putem apăra împotriva dușmanilor, creând în jurul nostru un mediu foarte special. Acest mediu este un spațiu sacru, dominat de puterea divină, ce strălucește și ne protejează de toate acele influențe pe care le simțim negative în viață.",
    detailsdn: "Nu avem o relație bună cu sfera noastră spirituală , se pare că am pierdut încrederea în existența noastră. De fapt, ne simțim persecutați de soartă, victimele nenumăratelor nedreptăți pe care le întâlnim, la mila unei lumi care pare un adversar misterios. Noi nu înțelegem sensul existenței și nu înțelegem ce sens poate avea încrederea în Dumnezeu. Trebuie să recâștigăm entuziasmul pentru viață, lumina speranței si credința în Dumnezeu, credința în noi înșine și în alții. Redescoperind tăcerea din noi , deschidem spațiul sacru care ne permite să comunicăm cu Dumnezeu, pentru a asculta cuvintele Lui, ce pot ilumina sufletul nostru umbrit.",
    keytitle: "Protecția rugăciunii",
    keyup: "protecție împotriva răului, conexiune cu divinul, trezire, sprijin, reușită.",
    keydn: "pericol ascuns, pierderea favorurilor și a legăturilor cu divinitatea, vulnerabilitate, pericol.",
    prev: "perthrc",
    next: "sowilo",
  },
  sowilo: {
    title: "Sowilo",
    image: "/pngs/SOWILO.png",
    keywords: "Realizarea obiectivelor • Putere",
    keywordsdn: "- - -",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Întărește puterea voinței. Facilitează eliberarea energiei proprii și exprimarea individualității. Insuflă încredere, determinare, optimism și entuziasm. Accelerează calea spre succes și întărește imunitatea.",
    messagetitle: "Mesajul:",
    message: "Pentru a decide modul de utilizare a energiei, trebuie să privim în interiorul nostru. Această alegere va avea consecințe neașteptate pentru noi înșine dar și pentru alții.",
    details: "Guvernată de Soare, reprezintă energia, puterea, lumina, căldura. Energia poate fi văzută atât într-o lumină pozitivă (care apare luminos, vital, solar) cât și cu sens negativ ( teribilă, înfricoșătoare, distructivă) Atunci când apare această rună, ne putem gândi la iluminare, la o idee genială care ne inundă ca un flash, la o realizare. Trăim un moment în care simțim că energia noastră este exprimată, este liberă să dizolve tensiunile: în cele din urmă , suntem impregnați de un sentiment de ușurare, iar acum ne putem relaxa. Ne îndreptăm spre iluminare și suntem în plină lumină, într-un succes complet, demonstrând altora adevărata noastră esență și identitate. Puterea acesteia energii poate fi utilizata în mai multe moduri: trebuie să fim atenți să o canalizăm într-un mod pozitiv, deoarece, dacă ne îndreptăm spre rău, ne poate distruge. Depinde de noi să alegem și să decidem modul în care gestionăm această mare putere care stă în noi: este necesar, de exemplu, să acordăm atenție ispitelor ce pot fi întâlnite, pentru a evita decizii pripite. Atenție la schimbări bruște, la atitudinea prea obraznică , arogantă și trufașă. Trebuie să ne calibrăm bine forța energiei noastre, astfel încât să poată să scoată în evidență tot ceea ce este pozitiv, luminos și prezent în noi înșine. Sowilo poate reprezenta, de asemenea, un ghid spiritual sau esența sentimentului nostru de sine, valoarea noastră, caracterul complet, toate fiind obținute prin unirea sinelui cu conștiința superioară. Această rună este un impuls pentru a ne autorealiza. Încrezându-ne în potențialul nostru, ne putem regăsi centrul.",
    detailsdn: " - - - ",
    keytitle: "Alegerea între bine și rău",
    keyup: "succes, putere, nepăsare, poftă de viață, energie, furie, conștientizare, caracter complet, autorealizare, fulger, foc purificator, autodistrugere.",
    keydn: "- - -",
    prev: "algiz",
    next: "tiewaz",
  },
  tiewaz: {
    title: "Tiewaz",
    image: "/pngs/TIEWAZ.png",
    keywords: "Victorie împotriva răului • Entuziasm",
    keywordsdn: "Concurență neloială • Randament redus • ",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Oferă protecție divină, curaj, voință puternică, încredere si responsabilitate pentru acțiunile proprii. Ne susține în fața nedreptății și ne apără de injustiție, ne învață să ne înțelegem granițele. Aduce echilibru in timpul luptei.",
    messagetitle: "Mesajul:",
    message: "Pofta de putere și de autoritate trebuie lăsate să moară. A deține virtutea înseamnă renunțarea la unele parți ale egoului nostru, nepotrivite în funcții de răspundere.",
    details: "Guvernată de Tyr, zeul războiului și fiul lui Odin. Reprezintă onoarea, adevărul, dreptatea, autoritatea, responsabilitatea. Suntem curajoși, ne exprimăm puterea personală și putem cuceri orice ne dorim, acționând cu dreptate si respectând ordinea lucrurilor. În plus, ne bucurăm de o sănătate excelentă, sistemul nostru imunitar este puternic, suntem echilibrați și posedăm altitudinea corectă pentru a câștiga. Am obținut ceea ce ne aparține cu inteligență, strategie, justiție, curaj, iar acum suntem admirați, respectați și plăcuți de mulți oameni. Ceea ce am realizat este întotdeauna gestionat într-un mod echilibrat , cu înțelepciune și cu dreptate. Am respectat toate regulile și acum ne putem bucura de succesul nostru.",
    detailsdn: "Trebuie să reflectăm asupra acțiunilor noastre deoarece se pare că ne învestim energiile în ceva care nu ne va duce nicăieri. Simțim oboseală, slăbiciune și se pare că ne lipsește capacitatea de a ne dirija ordonat și conștient viața. Trebuie înțeleasă bine motivația acțiunilor noastre: să știm care sunt ghidate de justiție sau din dorința de putere, bani, glorie, succes, recunoaștere. Trebuie să ne întrebăm care sunt sentimentele care ne emoționează în viața: dragoste și compasiune sau furie, invidie, mândrie, aroganță? Cel mai probabil, acțiunile noastre nu sunt conforme cu voința divină, din moment ce nu sunt prezente ordinea și justiția.",
    keytitle: "Războinicul luminii",
    keyup: "direcția cea bună, victorie, onoare, justiție, ordine, valoare, onestitate, câștig, responsabilitate.",
    keydn: "înfrângere, plata prețului pentru acțiunile noastre, sacrificiu, lipsă de onestitate, dezechilibru.",
    prev: "sowilo",
    next: "berkana",
  },
  berkana: {
    title: "Berkana",
    image: "/pngs/BERKANA.png",
    keywords: "Început • Realizare concretă",
    keywordsdn: "Regres • Încetinire • Stagnare",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Conferă vindecare, seninătate, stare psihofizică bună. Protejează noile uniuni, cuplul, familia. Insuflă echilibru, armonie și liniște în relații. Favoriează feritlitatea, procrearea și creativitatea. Încurajează și susține proiecte noi.",
    messagetitle: "Mesajul:",
    message: "Când ne regăsim contactul cu sufletul nostru și ascultăm vocea copilului interior, ne putem lua cu adevărat viața în propriile mâini.",
    details: "Guvernată de Freya, zeița fertilității, reprezintă noua viață, înflorirea evenimentelor. Dezvăluie purificarea, reînnoirea, exprimarea energiei sexuale, procrearea și ne conectează cu partea noastră feminină. Deține capacitatea de a accepta și de a dona viața, de a hrăni și de a proteja. Dacă trezim energiile receptive și feminine, ele amplifică percepția, capacitatea de a primi energiile cosmosului. După o perioadă de întuneric rece și steril, renaște în noi speranța și bucuria vieții. Promite probabil sosirea unei noi vieți: sau vom ajunge la un nou nivel de conștiință și ceva în noi se va naște, sau poate un vis va deveni realitate. Am regăsit tinerețea interioară.",
    detailsdn: "Impulsurile noastre creative sunt blocate și ne dăm seama că nu progresăm, că nu evoluăm. Nu reușim să simțim poezia și bucuria în viață, acele motivații care ne pot duce să avem încredere în existență. Suntem lipsiți de entuziasm , lăsându-ne înghițiți de plictiseală, de rutină și de obiceiuri. Totul pare fără sens, determinând o atitudine frigidă, sterilă, aridă. Nu mai putem să pătrundem în sufletul lucrurilor pentru că suntem fixați pe poziție, fără să vedem în perspectivă imagini pozitive. Trebuie să renunțăm la un control excesiv care nu duce la nimic.",
    keytitle: "Feminitatea",
    keyup: "un nou început, naștere, fertilitate, dorință, dragoste, vindecare, reproducere.",
    keydn: "imaturitate, anxietate, abandon, pierderea controlului, rigiditate, izolare excesivă.",
    prev: "tiewaz",
    next: "ehwaz",
  },
  ehwaz: {
    title: "Ehwaz",
    image: "/pngs/EHWAZ.png",
    keywords: "Colaborare • Îmbunătățire",
    keywordsdn: "Întârziere • Excludere • Probleme",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Întărește contactul cu sufletul nostru. Ne protejează în timpul călătoriilor sau când suntem în mișcare, promovând procesul de schimbare și de transformare a relațiilor. Aduce claritate, armonie și echilibru în relații, asigurând îmbunătățirea acestora.",
    messagetitle: "Mesajul:",
    message: "Prin relații, dacă ceilalți ne sunt oglinda sufletului nostru, putem găsi calea cea mai rapidă pentru creșterea și evoluția persoanei și a sufletului nostru.",
    details: "Guvernată de Sleippnir, calul lui Odin, relevă cooperarea, creșterea și colaborarea în relații. Reprezintă încredere reciprocă, loialitate și creșterea personală prin intermediul relațiilor, motiv pentru care această rună este denumită „Călătoria Sufletului”. Cu încredere în instinctele și în intuiția proprie, cu forță și energie, venim în contact cu ceilalți și stabilim cu ei o relație de înțelegere, de ascultare, de respect reciproc, de cooperare și schimb (la fel ca și relația dintre cal și călăreț). Ehwaz reprezintă un progres în relațiile pe care le experimentăm și le avem în vedere, pentru a promova schimbarea noastră și implicit, evoluția personală.",
    detailsdn: "Dezvăluie relații dizarmonice, agresivitate și conflicte. Este mult mai ușor să ne pierdem controlul pentru că există prietenii dăunătoare care duc la distrugerea relațiilor de muncă sau a relațiilor sentimentale. În plus, există o lipsă de claritate, de transparență și acest lucru crează nemulțumire, suspiciune, neîncredere. Nu ne putem alimenta și susține legăturile, din moment ce acordurile nu sunt respectate, nu există niciun fel de încredere, iar aceasta ar trebui să fie fundamentul tuturor relațiilor. Fără încredere ne asumăm rolurile și există riscul de a trăi doar o parte din noi. Trecând prin această experiență dificilă, reflectăm la ceea ce este greșit și putem să remediem și să restabilim ordinea în relațiile noastre.",
    keytitle: "Călătoria sufletului",
    keyup: "mișcare, îmbunătățire, armonie, cooperare, uniune de încredere, loialitate, înțelegere sexuală",
    keydn: "grabă, nechibzuință, trădări, ruptură, sentimente agitate sau inhibări, lipsă de armonie, neîncredere.",
    prev: "berkana",
    next: "mannaz",
  },
  mannaz: {
    title: "Mannaz",
    image: "/pngs/MANNAZ.png",
    keywords: "Armonie cu mediul",
    keywordsdn: "Refuz • Rigiditate • Izolare",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Întărește sentimentul de comuniune cu restul lumii. Hrănește coeziunea, cooperarea și ne permite să avem o atitudine de deschidere față de ceilalți. Crește capacitatea de a direcționa eforturile noastre spre binele comun. Promovează auto-realizarea.",
    messagetitle: "Mesajul:",
    message: "Nu trebuie să judecăm o carte după copertă, căci există riscul să facem greșeli. Simțind că facem parte din aceeași lume, ne putem accepta unii pe alții.",
    details: "Guvernată de Mannus-Vi, Zeul care dă conștiință oamenilor, reprezintă individul integrat în societate, înzestrat cu rațiune, cu inteligență și pe deplin conștient de legătura cu sfera divină. Putem recunoaște acele ființe umane creatoare și părtașe la lumea în care trăim. Dezvăluie individul realizat, în comunicare cu el însuși și cu alții, simbolizează umanitatea și trezește în oameni sentimentul de apartenență la un proiect, la un destin comun, excluzând prejudecățile rasiale, religioase sau sociale. Reprezintă abilitatea de a intra în contact cu alte persoane, de a depăși barierele și distincțiile, alimentând sentimentul de fraternitate. Suntem deschiși unul față de celălalt, deoarece ne putem vedea reflectați în ochii celorlalți.",
    detailsdn: "În acest moment nu suntem în comunicare cu noi înșine, cu ceilalți, cu sfera divină și nu ne valorificăm potențialul. Nu ne simțim ca făcând parte dintr-un întreg, dar simțim un sentiment de goliciune și de singurătate, avem senzația de separare de restul omenirii. Este ca o rană mai veche care încă sângerează, ecoul unei dureri din trecut, care încă se mai simte (o trădare, un abandon, o dezamăgire). Din acest motiv, nu putem trăi bucuriile iubirii și ale prieteniei. Probabil că încă suferim în urma efectelor unei educații rigide bazate pe competiție și individualism. Aceasta poate fi sursa prejudecăților față de ceilalți.",
    keytitle: "Sentimentul de integrare",
    keyup: "fraternitate, deschidere, dezvoltarea conștiinței, inteligență, conștientizare.",
    keydn: "prejudecăți rasiale, sociale și religioase, aroganță, rigiditate, izolare, fanatism.",
    prev: "ehwaz",
    next: "laguz",
  },
  laguz: {
    title: "Laguz",
    image: "/pngs/LAGUZ.png",
    keywords: "Schimbare • Energie • Evoluție",
    keywordsdn: "Iluzii • Intuiții false • Pericole",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Dezvoltă intuiția, capacitatea de a acea încredere în sentimentele și visele proprii. Crește capacitatea de a rămâne conectat la conștiința noastră. Încurajează exprimarea liberă a ideilor, a emoțiilor și a intențiilor. Atenuează gândul rigid și cristalizat.",
    messagetitle: "Mesajul:",
    message: "Uneori avem nevoie de un port sigur, să coborâm de pe vapor, din încleștarea valurilor și, mergând pe plajă, să ne bucurăm de căldura soarelui.",
    details: "Guvernată de Nijord, zeul mării, sursa vieții și a creației, simbolizează apa, fluxul de emoții și de energie, dezvăluie intuiția și imaginația. De asemenea, reprezintă inconștientul, locul unde putem găsi părțile noastre cele mai secrete și unde putem găsi resurse importante pentru viață, cunoaștere și înțelepciune. Acum suntem în comuniune cu sentimentele și cu emoțiile noastre și știm cp ele sunt de o mare bogăție. În plus, nu ne mai este frică de partea noastră întunecată și ne putem exprima în mod liber ființa. Suntem în comunicare cu ghidul interior și putem avea încredere în percepțiile, în sentimentele, în viziunile și în visele noastre.",
    detailsdn: "Suntem asaltați de frică și de estimările noastre greșite. Ne-am pierdut controlul emoțiilor și al instinctelor, așa încât trebuie să reluăm contactul cu realitatea. Am pierdut legătura cu stările noastre pozitive, cu strălucirea intuiției. Ne simțim deconectați de noi înșine, dezorientați, izolați și simțim că ne-am pierdut direcția. Ar trebui să recuperăm acel grad de conștientizare: cine suntem, într-adevăr, de unde venim, încotro mergem, restabilindu-ne comunicarea cu ghidul interior. Poate am absorbit aspecte mai neplăcute ale inconștientului colectiv, preluând negativismul care ne înconjoară, resimțindu-i toată greutatea.",
    keytitle: "Inconștientul colectiv",
    keyup: "creștere, intuiție, vis, fantezie, ocult, vindecare, mister, empatie, emoție.",
    keydn: "confuzie, decizie greșită, superficialitate, teamă, lipsă de creativitate, durere.",
    prev: "mannaz",
    next: "inguz",
  },
  inguz: {
    title: "Inguz",
    image: "/pngs/INGUZ.png",
    keywords: "Fericire • Serenitate • Entuziasm",
    keywordsdn: "- - -",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Este uniunea de familie. Oferă armonie în legăturile interpersonale, stabilitate în relații și căsătorii. Atrage abundența, ajută fertilitatea și creșterea bunurilor noastre materiale. Promovează noi proiecte, idei concrete, oferă determinarea și echilibrul corect într-o nouă etapă a vieții.",
    messagetitle: "Mesajul:",
    message: "Cultivându-ne pe noi înșine, le-am transferat celor dragi starea noastră pozitivă, iar acum ne putem bucura de fericirea lor și de bogăția recoltei.",
    details: "Guvernată de Ingwarr, zeul Luminii care prezidează curtea zeilor, dezvăluie ceva care, la momentul potrivit va simbola pregătirea și sosirea unei noi forme de viață. Aceasta indică renaștere, reînnoire, un nou început după o perioadă dificilă. Este rezolvarea problemelor, eliberarea de anxietate și de tensiune. Trebuie să lăsăm trecutul în urmă, obiceiurile, credințele și comportamentele care nu mai fac parte din noi și care ne constrâng evoluția. O nouă energie a intrat în viața noastră și își găsește expresia în relațiile interpersonale (în special, în cadrul familiei, între parteneri de viață sau între soți, între părinți și copii, frați și surori). Pot surveni schimbări importante: bașterea copiilor, o nouă șansă profesională, o nouă relație romantică. Culegem ce am semănat cu bucurie, cu dragoste și cu perseverență. Loialitatea și fidelitatea ce le-am arătat este recompensată. Trebuie să continuăm să menținem o atitudine corectă în relațiile noastre de familie, să nu lăsăm nimic nerezolvat. Toate conflictele să fie gestionate cu atenție și rezolvate în cel mai bun mod posibil, pentru a avea garanția unei vieți senine, pașnice, stabile și armonioase. Emoțiile noastre trebuie să-și găsească expresia corespunzătoare pentru a evita să transferăm durerea și suferința noastră asupra copiilor, asupra urmașilor și a generațiilor viitoare. Să lucrăm pe noi înșine pentru a oferi partea pozitivă celor din jurul nostru, în special celor pe care îi iubim cel mai mult. Înainte de toate, să punem în ordine interiorul nostru, pentru a putea oferi echilibru celorlalți.",
    detailsdn: " - - -",
    keytitle: "Focul sacru al neamului",
    keyup: "sexualitate, muncă, fertilitate, agricultură, pace, abundență, copii, virtute, bun-simț, vitalitate masculină, creștere internă, căldură umană.",
    keydn: "- - -",
    prev: "laguz",
    next: "dagaz",
  },
  dagaz: {
    title: "Dagaz",
    image: "/pngs/DAGAZ.png",
    keywords: "• Încredere •",
    keywordsdn: "- - -",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Aduce Lumina și abilitatea de a iubi viața și pe ceilalți. Promovează calea evoluției și accelerează procesul de vindecare. Ne ajută să ținem la distanță unele situații și oamenii ce nu mai sunt în ton cu drumul nostru evolutiv. Facilitează meditația.",
    messagetitle: "Mesajul:",
    message: "Aveți credință! A sosit momentul pentru a face un salt în gol. Din modul în care ne confruntăm cu această schimbare vor apărea caracteristicile de războinici.",
    details: "Guvernată de Dagr, zeul Luminii. În cele din urmă, Lumina triumfă în viața noastră. Binele a triumfat și o nouă conștientizare răsare la orizont. Dagaz relevă o transformare în procesul de căutare de sine, o schimbare radicală a propriului mod de viață. Pentru unii oameni, tranziția este atât de radicală, încât le schimbp complet existența. În viața fiecăruia apare un moment determinant, iar atunci când vine, dacă îl recunoaștem la timp și profităm de el, schimbarea ne va transforma cursul vieții pentru totdeauna. Dagaz promite o perioadă de rezultate bune și de prosperitate: întunericul a fost învins, Lumina începe să strălucească. Aceasta este o etapă de mare schimbare. Este începutul unei noi perioade care va surveni imediat și care va genera schimbări foarte importante și de durată asupra multor aspecte ale existenței noastre. Conștiința noastră se luminează și simțim o stare de bine și de liniște ce străbate întreaga noastră ființă. Este ca în prima zi a vieții noastre: o luăm de la capăt cu entuziasm! Schimbăm modul în care ne raportăm la lume, la ceilalți, la noi înșine. Ne vom schimba obiceiurile, vom scăpa de vechile atitudini depășite care ne îngreunează evoluția. Datoriile de viață se sting, creanțele sunt colectate, energia curge liberă și curată. Ne-am atins libertatea, am înțeles profund și ne-am dat seama că a sosit momentul pentru creșterea noastră la toate nivelurile, iar acum ne putem bucura de progresul propriu. Nu trebuie să ne fie teamă, vântul ne va ajuta să ne depășim propriile bariere!",
    detailsdn: "- - -",
    keytitle: "Noua eră",
    keyup: "lumina zilei, iluminare, transformare, claritate, începutul unui nou ciclu, sănătate, prosperitate, echilibru, dorință, securitate, trezire, creștere, speranță, conștietizare.",
    keydn: "- - -",
    prev: "inguz",
    next: "othala",
  },
  othala: {
    title: "Othala",
    image: "/pngs/OTHALA.png",
    keywords: "Beneficii • Stabilitate • Protecție",
    keywordsdn: "Condiționări vechi • Obiceiuri depășite",
    titleamulet: "Folosirea Runei ca Amuletă:",
    amulet: "Ne reconectează cu originile noastre și ne permite recăpătarea amintirilor și a talentelor vechi. Ne permite să primim energie, bunuri și beneficii de la strămoșii noștrii și ne oferă ajutorul lor pentru a proteja averea familiei, pentru păstrarea ei pentru generațiile viitoare.",
    messagetitle: "Mesajul:",
    message: "Să fim recunoscători pentru ceea ce am primit în trecut și să folosim totul în direcționarea mai bună a destinului nostru, al celor dragi, al întregii omeniri.",
    details: "Guvernată de Syn, zeița-gardian al porților de Mimir, gardian al fântânii înțelepciunii. Reprezintă tot ceea ce vine din familie (moștenirea materială, calitățiile spirituale și caracterul moștenit de la strămoșii noștrii), indicând obținerea drepturilor de proprietate, indiferent dacă acesta este un spațiu fizic sau este un rezultat. Reprezintă protecția și recunoașterea spațiului nostru, în care ne putem exprima și realiza. Această Rună ne arată că avem o realție bună cu originile noastre, cu oamenii care ne-au oferit ceva (la nivel sentimental, de muncă, de familie), reprezintă recunoștința față de ei. Așadar, acum vom obține o recompensă (moștenire, bani, bijuterii, case, terenuri sau diverse titluri).",
    detailsdn: "Indică un dispreț profund pentru cei dragi și lipsa de recunoștință față de tot ce reprezintă familie și propriile origini. Pierderm bunuri sau moșteniri, toate acestea pot fi efectul karmei negative personale sau a neamului. Ignorând greșelile făcute de noi sau de familia noastră de origine, ne încărcăm cu toate suferințele. Suntem încă victime ale unor situații dificile nerezolvate și nu putem face un salt înainte, așa încât să putem să luăm frâiele propriului destin într-o direcție pe care ne-o dorim. Ne simțim prizonierii unor condiționări vechi, care ne țin captivi într-o situație care pare să nu aibă nicio cale de ieșire.",
    keytitle: "Onorează-ți strămoșii",
    keyup: "posesiuni, prosperitate, familie, moștenire, națiune, patrimoniu, rădăcini, talente.",
    keydn: "rasism, lăcomie, sărăcie, provincialism, totalitarism, sclavie, prejudecată.",
    prev: "dagaz",
    next: "fehu",
  },
};
